-- ============================================================================
-- Create Internal Stages for dbt Bronze Layer Ingestion
-- ============================================================================
-- Purpose: Create internal stages for storing generated data files
-- Used by: dbt Bronze models to ingest data via COPY INTO
-- ============================================================================

USE ROLE DATA_ENGINEER;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE CUSTOMER_ANALYTICS;
USE SCHEMA BRONZE;

-- ============================================================================
-- Create Parquet File Format
-- ============================================================================

CREATE OR REPLACE FILE FORMAT parquet_format
  TYPE = 'PARQUET'
  COMPRESSION = 'SNAPPY'
  COMMENT = 'Parquet file format for internal stage data';

-- ============================================================================
-- Create Internal Stage: CUSTOMER_DATA_STAGE
-- ============================================================================

CREATE OR REPLACE STAGE customer_data_stage
  FILE_FORMAT = parquet_format
  COMMENT = 'Internal stage for customer data generated by GENERATE_CUSTOMERS procedure';

-- ============================================================================
-- Create Internal Stage: TRANSACTION_DATA_STAGE (Future Use)
-- ============================================================================

CREATE OR REPLACE STAGE transaction_data_stage
  FILE_FORMAT = parquet_format
  COMMENT = 'Internal stage for transaction data (future: streaming/incremental loads)';

-- ============================================================================
-- Verify Stages
-- ============================================================================

SHOW STAGES IN SCHEMA CUSTOMER_ANALYTICS.BRONZE;

-- ============================================================================
-- Test Stage Access
-- ============================================================================

-- List files in customer data stage (will be empty initially)
LIST @customer_data_stage;

-- ============================================================================
-- Grant Permissions
-- ============================================================================

-- Grant usage to DATA_ENGINEER (already has access as creator)
GRANT USAGE ON STAGE customer_data_stage TO ROLE DATA_ANALYST;
GRANT USAGE ON STAGE transaction_data_stage TO ROLE DATA_ANALYST;

GRANT READ ON STAGE customer_data_stage TO ROLE DATA_ANALYST;
GRANT READ ON STAGE transaction_data_stage TO ROLE DATA_ANALYST;

-- ============================================================================
-- View File Formats
-- ============================================================================

SHOW FILE FORMATS IN SCHEMA CUSTOMER_ANALYTICS.BRONZE;

-- ============================================================================
-- Usage Examples
-- ============================================================================

-- After running GENERATE_CUSTOMERS procedure, list generated files:
-- LIST @customer_data_stage;

-- Preview Parquet data:
-- SELECT * FROM @customer_data_stage (FILE_FORMAT => 'parquet_format') LIMIT 10;

-- Count records in Parquet file:
-- SELECT COUNT(*) FROM @customer_data_stage (FILE_FORMAT => 'parquet_format');

-- ============================================================================
-- Verification
-- ============================================================================

SELECT '✓ Internal stages created successfully' AS status;
SELECT 'customer_data_stage, transaction_data_stage' AS stages_created;
SELECT 'Next: Run CALL BRONZE.GENERATE_CUSTOMERS(50000, 42)' AS next_step;
