# ============================================================================
# dbt Project Configuration - Customer 360 Analytics
# ============================================================================
# Project: Customer 360 Analytics Platform
# Purpose: Transform Bronze → Silver → Gold layers
# Database: Snowflake
# ============================================================================

name: 'customer_analytics'
version: '1.0.0'
config-version: 2

# Project profile (must match profile name in profiles.yml)
profile: 'customer_analytics'

# Directory paths
model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
analysis-paths: ["analyses"]
snapshot-paths: ["snapshots"]

# Build artifacts
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

# ============================================================================
# Model Configurations
# ============================================================================

models:
  customer_analytics:
    # Default materialization strategy
    +materialized: table
    +schema: silver  # Default to silver schema

    # Staging models (Bronze → Silver)
    staging:
      +materialized: view  # Views for staging (lightweight)
      +schema: silver
      +tags: ["staging", "silver"]
      +docs:
        node_color: "#F4A460"  # Sandy brown for staging

    # Intermediate models (transformations within Silver)
    intermediate:
      +materialized: view
      +schema: silver
      +tags: ["intermediate", "silver"]
      +docs:
        node_color: "#87CEEB"  # Sky blue for intermediate

    # Mart models (Silver → Gold dimensional models)
    marts:
      +materialized: table
      +schema: gold
      +tags: ["mart", "gold"]
      +docs:
        node_color: "#FFD700"  # Gold for marts

      # Customer mart (fact and dimension tables)
      customer:
        +materialized: table
        +schema: gold
        +tags: ["customer", "mart", "gold"]

# ============================================================================
# Observability & Logging Hooks
# ============================================================================

# Run at the start of dbt execution
on-run-start:
  - "{{ log('╔══════════════════════════════════════════╗', info=True) }}"
  - "{{ log('║  dbt Run Started                        ║', info=True) }}"
  - "{{ log('║  Run ID: ' ~ invocation_id ~ '     ║', info=True) }}"
  - "{{ log('║  Timestamp: ' ~ run_started_at ~ '      ║', info=True) }}"
  - "{{ log('╚══════════════════════════════════════════╝', info=True) }}"

  # Log run start to observability table
  - "{% if target.name != 'test' %}
     INSERT INTO {{ target.database }}.OBSERVABILITY.PIPELINE_RUN_METADATA (
       run_id,
       run_timestamp,
       status,
       target_name,
       dbt_version
     )
     VALUES (
       '{{ invocation_id }}',
       '{{ run_started_at }}',
       'STARTED',
       '{{ target.name }}',
       '{{ dbt_version }}'
     )
     {% endif %}"

# Run at the end of dbt execution
on-run-end:
  # Log summary and update observability
  - "{% set models_run = results | length %}
     {% set models_failed = results | selectattr('status', 'equalto', 'error') | list | length %}
     {% set models_passed = models_run - models_failed %}
     {% set status = 'SUCCESS' if models_failed == 0 else 'FAILED' %}
     {{ log('', info=True) }}
     {{ log('╔══════════════════════════════════════════╗', info=True) }}
     {{ log('║  dbt Run Completed                      ║', info=True) }}
     {{ log('║  Status: ' ~ status ~ '                         ║', info=True) }}
     {{ log('║  Models Run: ' ~ models_run ~ '                       ║', info=True) }}
     {{ log('║  Passed: ' ~ models_passed ~ '   Failed: ' ~ models_failed ~ '           ║', info=True) }}
     {{ log('╚══════════════════════════════════════════╝', info=True) }}"

  # Update observability table with final status
  - "{% if target.name != 'test' %}
     {% set models_run = results | length %}
     {% set models_failed = results | selectattr('status', 'equalto', 'error') | list | length %}
     {% set models_passed = models_run - models_failed %}
     {% set status = 'SUCCESS' if models_failed == 0 else 'FAILED' %}
     UPDATE {{ target.database }}.OBSERVABILITY.PIPELINE_RUN_METADATA
     SET
       status = '{{ status }}',
       models_run = {{ models_run }},
       models_passed = {{ models_passed }},
       models_failed = {{ models_failed }},
       completed_timestamp = CURRENT_TIMESTAMP()
     WHERE run_id = '{{ invocation_id }}'
     {% endif %}"

# ============================================================================
# Seeds Configuration
# ============================================================================

seeds:
  customer_analytics:
    +schema: seeds
    +tags: ["seed"]
    +quote_columns: false

# ============================================================================
# Snapshots Configuration
# ============================================================================

snapshots:
  customer_analytics:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at
    +tags: ["snapshot"]

# ============================================================================
# Tests Configuration
# ============================================================================

tests:
  customer_analytics:
    +store_failures: true
    +schema: test_failures

# ============================================================================
# Quoting Configuration
# ============================================================================

quoting:
  database: false
  schema: false
  identifier: false

# ============================================================================
# Variables
# ============================================================================

vars:
  # Date range for incremental models
  start_date: "2022-01-01"

  # Customer segmentation thresholds
  high_value_threshold: 10000  # Annual spend

  # Churn definition (days since last transaction)
  churn_days: 90

# ============================================================================
# Dispatch Configuration (for packages)
# ============================================================================

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['customer_analytics', 'dbt_utils']
